cmake_minimum_required(VERSION 3.15)
project(GhostProxifier)
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded")
set(CMAKE_CXX_STANDARD 17)
include_directories(minhook/include)
add_subdirectory(minhook)
add_library(ghost_core SHARED ghost_core.cpp)
add_executable(ghost-proxifier WIN32 ghost_injector.cpp)
add_executable(ghost-proxifier-console ghost_injector.cpp)
target_compile_definitions(ghost-proxifier PRIVATE GHOST_GUI_BUILD)
target_link_libraries(ghost_core minhook ws2_32)
target_link_libraries(ghost-proxifier ws2_32 psapi shell32 user32)
target_link_libraries(ghost-proxifier-console ws2_32 psapi shell32 user32)

if(MSVC)
  target_compile_options(ghost_core PRIVATE /utf-8)
  target_compile_options(ghost-proxifier PRIVATE /utf-8)
  target_compile_options(ghost-proxifier-console PRIVATE /utf-8)
endif()
