#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use serde::{Deserialize, Serialize};
use std::{
    fs,
    io::{BufRead, BufReader},
    path::{Path, PathBuf},
    process::{Child, Command, Stdio},
    sync::{Arc, Mutex},
    thread,
};
use tauri::{AppHandle, Emitter, Manager, State};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct AppConfig {
    auto_start: bool,
    proxy: String,
    targets: Vec<String>,
    watch: bool,
    restore_on_exit: bool,
}

impl Default for AppConfig {
    fn default() -> Self {
        Self {
            auto_start: false,
            proxy: "127.0.0.1:2080".into(),
            targets: vec![],
            watch: true,
            restore_on_exit: true,
        }
    }
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct RuntimeStatus {
    running: bool,
    config: AppConfig,
    logs: Vec<String>,
}

#[derive(Default)]
struct RuntimeState {
    child: Option<Child>,
    logs: Vec<String>,
    config: AppConfig,
}

type SharedState = Arc<Mutex<RuntimeState>>;

const APP_NAME: &str = "GhostProxifierUI";

fn config_path(app: &AppHandle) -> Result<PathBuf, String> {
    Ok(app
        .path()
        .app_config_dir()
        .map_err(|e| e.to_string())?
        .join("ui-config.json"))
}

fn runtime_dir(app: &AppHandle) -> Result<PathBuf, String> {
    Ok(app
        .path()
        .app_data_dir()
        .map_err(|e| e.to_string())?
        .join("runtime"))
}

fn load_config(app: &AppHandle) -> AppConfig {
    let mut cfg = config_path(app)
        .ok()
        .and_then(|p| fs::read_to_string(p).ok())
        .and_then(|s| serde_json::from_str::<AppConfig>(&s).ok())
        .unwrap_or_default();
    cfg.auto_start = query_autostart().unwrap_or(false);
    cfg
}

fn save_config_to_disk(app: &AppHandle, cfg: &AppConfig) -> Result<(), String> {
    let path = config_path(app)?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    fs::write(path, serde_json::to_string_pretty(cfg).map_err(|e| e.to_string())?)
        .map_err(|e| e.to_string())
}

fn find_project_asset(app: &AppHandle, name: &str) -> Option<PathBuf> {
    let mut candidates = Vec::new();
    if let Ok(resource) = app.path().resolve(
        format!("bin/{name}"),
        tauri::path::BaseDirectory::Resource,
    ) {
        candidates.push(resource);
    }
    if let Ok(exe) = std::env::current_exe() {
        if let Some(dir) = exe.parent() {
            candidates.push(dir.join(name));
            candidates.push(dir.join("bin").join(name));
        }
    }
    if let Ok(mut cwd) = std::env::current_dir() {
        for _ in 0..5 {
            candidates.push(cwd.join("bin").join(name));
            candidates.push(cwd.join(name));
            if !cwd.pop() {
                break;
            }
        }
    }
    candidates.into_iter().find(|p| p.exists())
}

fn ensure_runtime(app: &AppHandle) -> Result<PathBuf, String> {
    let dir = runtime_dir(app)?;
    fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    for name in ["ghost-proxifier.exe", "ghost_core.dll"] {
        let dst = dir.join(name);
        let src = find_project_asset(app, name)
            .ok_or_else(|| format!("找不到 {name}。请先运行 compile.bat 生成 bin\\{name}，或把它放到程序资源目录。"))?;
        fs::copy(&src, &dst).map_err(|e| format!("复制 {src:?} 到 {dst:?} 失败：{e}"))?;
    }
    Ok(dir)
}

fn write_ghost_conf(dir: &Path, cfg: &AppConfig) -> Result<(), String> {
    let mut content = String::new();
    content.push_str("# Generated by Ghost Proxifier Tauri UI\n");
    content.push_str(&format!("proxy={}\n", cfg.proxy.trim()));
    for target in &cfg.targets {
        let t = target.trim();
        if !t.is_empty() {
            content.push_str(&format!("process={t}\n"));
        }
    }
    fs::write(dir.join("ghost.conf"), content).map_err(|e| e.to_string())
}

fn push_log(app: &AppHandle, state: &SharedState, line: String) {
    {
        let mut guard = state.lock().unwrap();
        guard.logs.push(line.clone());
        if guard.logs.len() > 2000 {
            let excess = guard.logs.len() - 2000;
            guard.logs.drain(0..excess);
        }
    }
    let _ = app.emit("ghost-log", line);
}

#[cfg(windows)]
fn creation_flags(cmd: &mut Command) -> &mut Command {
    use std::os::windows::process::CommandExt;
    const CREATE_NO_WINDOW: u32 = 0x08000000;
    cmd.creation_flags(CREATE_NO_WINDOW)
}

#[cfg(not(windows))]
fn creation_flags(cmd: &mut Command) -> &mut Command {
    cmd
}

fn build_args(cfg: &AppConfig) -> Vec<String> {
    let mut args = Vec::new();
    for target in cfg.targets.iter().map(|s| s.trim()).filter(|s| !s.is_empty()) {
        args.push("-p".into());
        args.push(target.into());
    }
    args.push("-u".into());
    args.push(cfg.proxy.trim().into());
    if cfg.watch {
        args.push("--watch".into());
    }
    args
}

fn run_restore(app: &AppHandle, cfg: &AppConfig) -> Result<String, String> {
    let dir = ensure_runtime(app)?;
    write_ghost_conf(&dir, cfg)?;
    let mut cmd = Command::new(dir.join("ghost-proxifier.exe"));
    cmd.current_dir(&dir).arg("--uninject");
    for target in cfg.targets.iter().map(|s| s.trim()).filter(|s| !s.is_empty()) {
        cmd.arg("-p").arg(target);
    }
    let output = creation_flags(&mut cmd)
        .output()
        .map_err(|e| format!("恢复进程状态失败：{e}"))?;
    Ok(String::from_utf8_lossy(&output.stdout).to_string())
}

fn stop_proxy_inner(app: &AppHandle, state: &SharedState) -> Result<(), String> {
    let cfg;
    {
        let mut guard = state.lock().unwrap();
        cfg = guard.config.clone();
        if let Some(mut child) = guard.child.take() {
            let _ = child.kill();
            let _ = child.wait();
        }
    }
    if cfg.restore_on_exit {
        if let Ok(out) = run_restore(app, &cfg) {
            for line in out.lines() {
                push_log(app, state, line.to_string());
            }
        }
    }
    Ok(())
}

#[tauri::command]
fn get_status(app: AppHandle, state: State<'_, SharedState>) -> Result<RuntimeStatus, String> {
    let mut guard = state.lock().unwrap();
    guard.config.auto_start = query_autostart().unwrap_or(false);
    if guard.config.targets.is_empty() && guard.logs.is_empty() {
        guard.config = load_config(&app);
    }
    Ok(RuntimeStatus {
        running: guard.child.is_some(),
        config: guard.config.clone(),
        logs: guard.logs.clone(),
    })
}

#[tauri::command]
fn save_config(
    app: AppHandle,
    state: State<'_, SharedState>,
    config: AppConfig,
) -> Result<AppConfig, String> {
    set_autostart_enabled(config.auto_start)?;
    save_config_to_disk(&app, &config)?;
    state.lock().unwrap().config = config.clone();
    Ok(config)
}

#[tauri::command]
fn start_proxy(
    app: AppHandle,
    state: State<'_, SharedState>,
    config: AppConfig,
) -> Result<(), String> {
    if config.proxy.trim().is_empty() {
        return Err("代理地址不能为空，例如 127.0.0.1:2080".into());
    }
    if config.targets.iter().all(|t| t.trim().is_empty()) {
        return Err("至少添加一个进程名或 PID".into());
    }

    stop_proxy_inner(&app, state.inner())?;
    set_autostart_enabled(config.auto_start)?;
    save_config_to_disk(&app, &config)?;

    let dir = ensure_runtime(&app)?;
    write_ghost_conf(&dir, &config)?;
    let args = build_args(&config);
    let exe = dir.join("ghost-proxifier.exe");

    let mut cmd = Command::new(exe);
    cmd.current_dir(&dir)
        .args(args)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());
    let mut child = creation_flags(&mut cmd)
        .spawn()
        .map_err(|e| format!("启动 ghost-proxifier.exe 失败：{e}"))?;

    let stdout = child.stdout.take();
    let stderr = child.stderr.take();

    {
        let mut guard = state.lock().unwrap();
        guard.config = config.clone();
        guard.child = Some(child);
    }

    let shared = state.inner().clone();
    if let Some(out) = stdout {
        let app2 = app.clone();
        let shared2 = shared.clone();
        thread::spawn(move || {
            for line in BufReader::new(out).lines().flatten() {
                push_log(&app2, &shared2, line);
            }
        });
    }
    if let Some(err) = stderr {
        let app2 = app.clone();
        let shared2 = shared.clone();
        thread::spawn(move || {
            for line in BufReader::new(err).lines().flatten() {
                push_log(&app2, &shared2, format!("[stderr] {line}"));
            }
        });
    }
    Ok(())
}

#[tauri::command]
fn stop_proxy(app: AppHandle, state: State<'_, SharedState>) -> Result<(), String> {
    stop_proxy_inner(&app, state.inner())
}

#[tauri::command]
fn restore_processes(app: AppHandle, state: State<'_, SharedState>) -> Result<String, String> {
    let cfg = state.lock().unwrap().config.clone();
    let out = run_restore(&app, &cfg)?;
    for line in out.lines() {
        push_log(&app, state.inner(), line.to_string());
    }
    Ok(out)
}

#[tauri::command]
fn set_auto_start(app: AppHandle, state: State<'_, SharedState>, enabled: bool) -> Result<bool, String> {
    set_autostart_enabled(enabled)?;
    let mut guard = state.lock().unwrap();
    guard.config.auto_start = enabled;
    let cfg = guard.config.clone();
    drop(guard);
    save_config_to_disk(&app, &cfg)?;
    Ok(enabled)
}

#[cfg(windows)]
fn query_autostart() -> Result<bool, String> {
    let mut cmd = Command::new("reg");
    let output = creation_flags(&mut cmd)
        .args(["query", r"HKCU\Software\Microsoft\Windows\CurrentVersion\Run", "/v", APP_NAME])
        .output()
        .map_err(|e| e.to_string())?;
    Ok(output.status.success())
}

#[cfg(not(windows))]
fn query_autostart() -> Result<bool, String> {
    Ok(false)
}

#[cfg(windows)]
fn set_autostart_enabled(enabled: bool) -> Result<(), String> {
    let exe = std::env::current_exe().map_err(|e| e.to_string())?;
    let exe_value = format!("\"{}\"", exe.to_string_lossy());
    let mut cmd = Command::new("reg");
    if enabled {
        cmd.arg("add")
            .arg(r"HKCU\Software\Microsoft\Windows\CurrentVersion\Run")
            .arg("/v")
            .arg(APP_NAME)
            .arg("/t")
            .arg("REG_SZ")
            .arg("/d")
            .arg(exe_value)
            .arg("/f");
    } else {
        cmd.args([
            "delete",
            r"HKCU\Software\Microsoft\Windows\CurrentVersion\Run",
            "/v",
            APP_NAME,
            "/f",
        ]);
    }
    let status = creation_flags(&mut cmd).status().map_err(|e| e.to_string())?;
    if status.success() || !enabled {
        Ok(())
    } else {
        Err("写入开机启动注册表失败".into())
    }
}

#[cfg(not(windows))]
fn set_autostart_enabled(_enabled: bool) -> Result<(), String> {
    Ok(())
}

fn main() {
    tauri::Builder::default()
        .setup(|app| {
            let cfg = load_config(&app.handle());
            app.manage(Arc::new(Mutex::new(RuntimeState {
                child: None,
                logs: Vec::new(),
                config: cfg,
            })));
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            get_status,
            save_config,
            start_proxy,
            stop_proxy,
            restore_processes,
            set_auto_start
        ])
        .on_window_event(|window, event| {
            if let tauri::WindowEvent::CloseRequested { .. } = event {
                if let Some(state) = window.app_handle().try_state::<SharedState>() {
                    let _ = stop_proxy_inner(window.app_handle(), state.inner());
                }
            }
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
